### ISSUE TITLE
v3.9.4 kills Android WebView implementations in Android 10

### ISSUE THREAD

**Issue by Mygod** [eritpchy/Fingerprint-pay-magisk-wechat#10]
To reproduce:

1. Go to developer options and verify that WebView implementation is set to Android System WebView (or anything);
2. Enable this module in Magisk;
3. Reboot;
4. Go to developer options and verify that WebView implementation is now stuck to none since there are no options to pick from, and browser-based apps like Steam crash consistently.

System: Android 10 (OxygenOS 10.0, OnePlus 6)
Magisk: 20.1 (20100)

**Comment by mokwaichun** [comment]
none yet

**Comment by Mygod** [comment]
v3.9.5 seemed to have fixed it.
