### ISSUE TITLE
在Magisk v20.2 上无法正常工作

### ISSUE THREAD

**Issue by pssyz** [eritpchy/Fingerprint-pay-magisk-wechat#12]
在Magisk v20.2 上无法正常工作 ，微信设置中不显示指纹设置选项
使用的都是riru core 19.5 版本，和最新的Fingerprint-pay-magisk-wechat模块，微信 7.0.10，乐视 乐Max 2  ，Android 10 , 这些都是完全相同的情况下，一旦退回到Magisk v20.1，一切都恢复正常！
Fingerprint-pay-magisk-alipay也是这个情况！

**Comment by MelanPrince** [comment]
一加7T 同样。
20.1 的 Magisk 正常 但是 20.1 的 很容易不开机 之后的 debug 版本 不起作用。

magisk 确实有好多插件都不管用了。不知道算谁的bug。

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/commit/1aece77a687c698c67e800d016624ec9e63d3448
