### ISSUE TITLE
在新的Magisk 20.2上，微信模块无法正常工作

### ISSUE THREAD

**Issue by Jiaochengping** [eritpchy/Fingerprint-pay-magisk-wechat#13]
已经删除旧的模块，替换了新的update-binary，并重新安装。同时riru Core已经更新到19.6，可指纹模块还是不可用。

**Comment by freelf** [comment]
同样，不能用，Magisk 20.2，支付宝的也不能用

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/commit/1aece77a687c698c67e800d016624ec9e63d3448
