### ISSUE TITLE
如何自检模块是否运行正常

### ISSUE THREAD

**Issue by NewBugger** [eritpchy/Fingerprint-pay-magisk-wechat#14]
分别安装微信/淘宝/支付宝三个 riru 支付模块均不生效，设置菜单内没有本应 hook 进的“指纹支付”项

使用 xp 模块时均能成功使用

magisk 20.2 + riru core 15.6 + 支付模块最新

不知道该如何看 logcat 自检

**Comment by eritpchy** [comment]
magisk 请升级至20.3
riru core 请升级至19.6
