### ISSUE TITLE
模块失效

### ISSUE THREAD

**Issue by Roiyaru** [eritpchy/Fingerprint-pay-magisk-wechat#15]
在安卓10，Magisk Cancry ce7cb1ee，Riru-core19.7环境下模块失效，
微信是play703版本，
还有支付宝模块也一样失效

**Comment by eritpchy** [comment]
感谢反馈

**Comment by jeremiesun** [comment]
三星s10，edxposed，指纹支付正常，但是切换密码输入时无法输入密码

**Comment by eritpchy** [comment]
Cancry  分支不打算支持

**Comment by Roiyaru** [comment]
> Cancry 分支不打算支持

好的，但希望开发者在考虑一下。

**Comment by eritpchy** [comment]
嗯
