### ISSUE TITLE
无法适配v20.3？

### ISSUE THREAD

**Issue by pinoyo** [eritpchy/Fingerprint-pay-magisk-wechat#16]
如题，v20.3 导入这两个模块失败，谢谢

**Comment by eritpchy** [comment]
本来就支持20.3

**Comment by pinoyo** [comment]
![a5d554c851011fa592002e7dbeba335](https://user-images.githubusercontent.com/37075925/74903468-f6b59b80-53e3-11ea-9b74-0e76c574cda4.png)
![2275a63d2ebdea2b9fa5fe9c3c96cb4](https://user-images.githubusercontent.com/37075925/74903480-fd441300-53e3-11ea-867a-42ad10fb0ef6.png)
谢谢大侠

**Comment by pinoyo** [comment]
提示riru core 损坏，我下载了几遍

**Comment by pinoyo** [comment]
成了，是文件坏了，我直接从github链接下载就没问题了，还是要感谢您的提供，谢谢
