### ISSUE TITLE
无法输入数字密码

### ISSUE THREAD

**Issue by jeremiesun** [eritpchy/Fingerprint-pay-magisk-wechat#17]
三星s10，edxposed，指纹支付正常，但是切换密码输入时无法输入密码。试过了magisk版本和xposed版本都不行呢

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/commit/a63c9b32b8fbca18025ced88833bfeb1bbbb0ae0
