### ISSUE TITLE
sim卡失效

### ISSUE THREAD

**Issue by Qiyue0726** [eritpchy/Fingerprint-pay-magisk-wechat#18]
安装启动模块后重启手机，无法检测到sim卡，停用模块后又可以了
手机是一加3，官方最新稳定版安卓9.0，magisk是20.3版本

**Comment by SqueezeDc** [comment]
支持20.3的面具吗？

**Comment by eritpchy** [comment]
支持

**Comment by SqueezeDc** [comment]
已成功使用，20.3支持的三星note8

**Comment by ihkc** [comment]
> 安装启动模块后重启手机，无法检测到sim卡，停用模块后又可以了
> 手机是一加3，官方最新稳定版安卓9.0，magisk是20.3版本

重启一下就好了

**Comment by eritpchy** [comment]
建议更新系统, 如还有问题再开ISSUE
