### ISSUE TITLE
在 Magisk 20.4 上失效

### ISSUE THREAD

**Issue by Lutra-Fs** [eritpchy/Fingerprint-pay-magisk-wechat#19]
无法在面具20.4上使用

**Comment by Acris** [comment]
+1
目前的解决版本是先刷20.3，安装完模块再升级到20.4即可。

**Comment by yasin1151** [comment]
+1

**Comment by Lutra-Fs** [comment]
暂时的解决方案：
1. 回退 **Magisk 20.3**
2. 感谢 *酷安@情非得已c*，搞机助手兼容刷入模块即可 

我可能周末有时间会看下模块，就看自己能不能搞定了

**Comment by eritpchy** [comment]
![Screenrecorder-2020-04-03-21-13-04-516](https://user-images.githubusercontent.com/8630635/78367890-5c0cc700-75f5-11ea-96ce-290c0a8c7d89.gif)
不是可以吗

**Comment by Acris** [comment]
@eritpchy 如果模块是在20.4之前安装的，升级到20.4之后可以正常使用。
你可以尝试卸载模块，然后在20.4下安装，会发现装完后模块的名称显示不正确，而且版本号、作者、描述等都不显示，也不能正常使用。

**Comment by eritpchy** [comment]
1. 录屏就是全新安装的magisk 20.4, riru core, 指纹插件3.9.7(我本身并不用magisk，框架等等
2. 回复之前我还特意测试了卸载所有插件再安装，依然一切正常
3. 我还顺便升级Magisk Magisk MD2又测了一遍， 依然一切正常

**Comment by eritpchy** [comment]
用Root Explorer 进以下目录分别截图给我看看
1. /data/misc/riru/modules/module_xfingerprint_pay_wechat/
2. /data/adb/modules/riru-module-xfingerprint-pay-wechat/
以及文件属性截图
1. /data/adb/modules/riru-module-xfingerprint-pay-wechat/module.prop
2. /data/adb/modules/riru-core/module.prop

**Comment by eritpchy** [comment]
用Root Explorer 进以下目录分别截图给我看看
1. /data/misc/riru/modules/module_xfingerprint_pay_wechat/
2. /data/adb/modules/riru-module-xfingerprint-pay-wechat/
以及文件属性截图
1. /data/adb/modules/riru-module-xfingerprint-pay-wechat/module.prop
2. /data/adb/modules/riru-core/module.prop


文件属性截图例子
![6191585970458_ pic](https://user-images.githubusercontent.com/8630635/78417651-c9a50b80-7666-11ea-80fe-0353b0b2e8b8.jpg)

**Comment by Simle** [comment]
没有第三个文件

**Comment by eritpchy** [comment]
那有什么 截图呢?

**Comment by Simle** [comment]
![Screenshot_20200404-115744](https://user-images.githubusercontent.com/3889789/78418116-c3655e00-766b-11ea-8c9a-445900b3d534.png)
module.prop是从你的包里手动拷贝进去的,然后magisk里显示了模块描述,但是微信上没找到对应的菜单

**Comment by eritpchy** [comment]
重装插件 截图安装信息

**Comment by Simle** [comment]
![Screenshot_20200404-120352](https://user-images.githubusercontent.com/3889789/78418186-7e8df700-766c-11ea-98c7-2a7310c17af4.png)
安装log：
``
- Copying zip to temp directory
- Installing magisk-riru-module-xfingerprint-pay-wechat-v3.9.7.zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
******************************
 Riru - 指纹支付 - 微信 
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
******************************
*******************
 Powered by Magisk 
*******************
- Device platform: arm64
- Riru API version: 4
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
  inflating: module.prop
  inflating: uninstall.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop.sha256sum
- Verified module.prop
mv: can't create '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/module.prop': Permission denied
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh.sha256sum
- Verified post-fs-data.sh
mv: can't create '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/post-fs-data.sh': Permission denied
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh.sha256sum
- Verified uninstall.sh
mv: can't create '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/uninstall.sh': Permission denied
- Extracting arm/arm64 libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: system/
   creating: system/lib64/
  inflating: system/lib64/libriru_module_xfingerprint_pay_wechat.so.sha256sum
  inflating: system/lib64/libriru_module_xfingerprint_pay_wechat.so
   creating: system/framework/
  inflating: system/framework/libxfingerprint_pay_wechat.dex.sha256sum
  inflating: system/framework/libxfingerprint_pay_wechat.dex
   creating: system/lib/
  inflating: system/lib/libriru_module_xfingerprint_pay_wechat.so.sha256sum
  inflating: system/lib/libriru_module_xfingerprint_pay_wechat.so
- Verified system/framework/libxfingerprint_pay_wechat.dex
mv: can't create '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/system/framework/libxfingerprint_pay_wechat.dex': Permission denied
- Verified system/lib/libriru_module_xfingerprint_pay_wechat.so
mv: can't create '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/system/lib/libriru_module_xfingerprint_pay_wechat.so': Permission denied
- Verified system/lib64/libriru_module_xfingerprint_pay_wechat.so
mv: can't create '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/system/lib64/libriru_module_xfingerprint_pay_wechat.so': Permission denied
- Extracting extra files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: data/
   creating: data/misc/
   creating: data/misc/riru/
   creating: data/misc/riru/modules/
   creating: data/misc/riru/modules/module_xfingerprint_pay_wechat/
  inflating: data/misc/riru/modules/module_xfingerprint_pay_wechat/module.prop.new.sha256sum
  inflating: data/misc/riru/modules/module_xfingerprint_pay_wechat/module.prop.new
- Setting permissions
cp: can't stat '/data/adb/modules_update/riru-module-xfingerprint-pay-wechat/module.prop': No such file or directory
- Done

**Comment by Simle** [comment]
![Screenshot_20200404-120352](https://user-images.githubusercontent.com/3889789/78418215-c3199280-766c-11ea-9cac-bc8c98e4ada0.png)

**Comment by eritpchy** [comment]
@Simle +Q276308768

**Comment by Acris** [comment]
安装了QQ指纹模块进行测试，这是安装完重启后在Magisk Manager里面的显示：
![1.jpg](https://i.loli.net/2020/04/04/TjtsZkgm27eY5R4.jpg)
可以看到名称、作者、版本、描述显示都有问题。

这是`/data/misc/riru/modules/module_xfingerprint_pay_qq/`的截图，和微信支付模块对比过，看起来是正常的：
![2.jpg](https://i.loli.net/2020/04/04/UakImPotcT2SQjv.jpg) 

这是`/data/adb/modules/riru-module-xfingerprint-pay-qq/`中的截图，和其他模块对比，缺少了一些属性文件，仅有system目录，怀疑就是这里的问题：
![3.jpg](https://i.loli.net/2020/04/04/XbL6Gl1FvQU4KDr.jpg)

由于上面目录缺少文件，所以后面的文件属性我没截图了，可以先看看为什么只有system目录。

**Comment by eritpchy** [comment]
@Acris 看起来是一样的问题

**Comment by eritpchy** [comment]
试试看
[magisk-riru-module-xfingerprint-pay-wechat-v3.9.7-test.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4430824/magisk-riru-module-xfingerprint-pay-wechat-v3.9.7-test.zip)

**Comment by N2022062** [comment]
> @Acris 看起来是一样的问题

Wechat可以

**Comment by thethreeonee** [comment]
实际依旧不能使用
用这个 3.9.7-test 的包，虽然可以在面具里显示模块信息了，但是微信里依旧没有指纹选项，实际支付时也并不能使用指纹识别


手机型号：OnePlus 8 Pro
系统版本：Hydrogen OS 10.5.4.IN11
安卓版本：10
Magisk 版本：20.4 (20400)
Riru Core 版本：19.8

**Comment by eritpchy** [comment]
微信版本手机系统版本

**Comment by thethreeonee** [comment]
> 微信版本手机系统版本

微信版本：7.0.13
系统版本：Hydrogen OS 10.5.4.IN11
安卓版本：10
手机系统内核版本：4.19.81-perf+
基带版本：MPSS.HI.1.0.c8.10-00002-SDX55_RMTEFS_PACK-2.267326.27
安全补丁级别：2020年3月1日

**Comment by LRYsboyfriend** [comment]
我有一样的问题，我的手机是pixel3，安卓10系统。magisk20.4

**Comment by ihkc** [comment]
不能生效是否跟使用了Riru-Enhanced mode for Storage Isolation（Storage Redirect）有关系？
同样是Oneplus 8Pro，降级了Magisk到20.2和20.3依然不能使用，微信支付始终没有显示设置选项。

**Comment by ghost** [comment]
同样的问题，降级到20.3安装后和升级到20.4在支付宝内都没有设置选项。
oneplus 8。
微信版本 7.0.13

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/commit/15bb1df80920253ddfdf9abe69adc7a146e63bc5
