### ISSUE TITLE
是否有可能做一个面容支付？

### ISSUE THREAD

**Issue by neo16ye** [eritpchy/Fingerprint-pay-magisk-wechat#20]
pixel 4手机没有指纹模块

**Comment by eritpchy** [comment]
从技术的角度来说是完全可行的, 但
试想一下别人要是用一张照片就能骗过面容识别的话你还想要吗?

**Comment by Ahua9527** [comment]
> 从技术的角度来说是完全可行的，但
> 试想一下别人要是用一张照片就能骗过过面容识别的话你还想要吗？

想

**Comment by eritpchy** [comment]
加油去写吧，看好你

**Comment by KGB333** [comment]
> 从技术的角度来说是完全可行的, 但
> 试想一下别人要是用一张照片就能骗过面容识别的话你还想要吗?

就是说其实是能实现只是大佬缺少开发工具对吗？
