### ISSUE TITLE
一加8pro无法使用微信指纹支付

### ISSUE THREAD

**Issue by crazyng6** [eritpchy/Fingerprint-pay-magisk-wechat#22]
一加8pro，氧OS10.5.6，Magisk20.4，安装的指纹模块是3.9.10，进微信设置并没有找到指纹支付选项。。。

**Comment by eritpchy** [comment]
riru core 什么版本

**Comment by crazyng6** [comment]
> riru core 什么版本

21.1

**Comment by 0X0000005** [comment]
我也是 同一加8 pro
Magisk 20.4
Riru-Core 21.1
指纹模块 Magisk内显示正常，但是在微信中无法看到指纹设置

**Comment by AustinLiu7** [comment]
相同问题，一加8
magisk20.4
riru-core 21.0

**Comment by eritpchy** [comment]
上传日志

**Comment by 0X0000005** [comment]
> 上传日志

请问在哪获取日志

**Comment by eritpchy** [comment]
adb logcat

**Comment by Vv7er** [comment]
我以为是我一个人的问题 看来一加8 pro都无法使用

**Comment by Mirr0ch1** [comment]
同，一加8Pro 无法使用微信、支付宝、淘宝指纹模块。。。 @eritpchy 请问大概需要哪方面的日志？

**Comment by matosman** [comment]
[logcat_05-09-2020_09-55-25.txt](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4602461/logcat_05-09-2020_09-55-25.txt)
hopes it can help

**Comment by eritpchy** [comment]
@matosman 这个日志并没有记录到任何和插件有关的信息, 请开始记录日志后, 进入指纹支付设置, 尝试支付过程

**Comment by eritpchy** [comment]
猜测是Riru的问题
1. 检查下以下文件是否存在
/system/framework/libriru_module_xfingerprint_pay_wechat.dex
/system/lib/libmemtrack.so

2. 尝试riru刚更新的21.2版本
https://github.com/RikkaApps/Riru/releases

**Comment by ihkc** [comment]
> 猜测是Riru的问题
> 
> 1. 检查下以下文件是否存在
>    /system/framework/libriru_module_xfingerprint_pay_wechat.dex
>    /system/lib/libmemtrack.so
> 2. 尝试riru刚更新的21.2版本
>    https://github.com/RikkaApps/Riru/releases

文件都在，更新最新Riru也沒用…

**Comment by eritpchy** [comment]
下载这个zip 解压 安装到手机上 打开并截图
[RiruManager-19.4-97-moe.riru.manager.apk.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4602665/RiruManager-19.4-97-moe.riru.manager.apk.zip)

**Comment by Mirr0ch1** [comment]
提示 riru not found in memory。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by eritpchy** [comment]
所以这是Riru的问题, 请等待Riru更新或者使用Xposed版指纹支付https://github.com/eritpchy/Xposed-Fingerprint-pay

**Comment by eritpchy** [comment]
试试EdXposed 能不能正常使用, EdXposed同样使用Riru
https://www.oneplusbbs.com/thread-5388651-1.html
https://www.oneplusbbs.com/thread-5385121-1.html

试试连接中的版本 magisk-riru-core-v19.8.zip

**Comment by 0X0000005** [comment]
刚刚试了EdXposed的没问题
其他一些Xposed插件没什么问题

**Comment by eritpchy** [comment]
riru什么版本

**Comment by 0X0000005** [comment]
> riru什么版本

最新的 21.2

**Comment by eritpchy** [comment]
装上Xposed的指纹支付能用吗

**Comment by 0X0000005** [comment]
> 装上Xposed的指纹支付能用吗

可以正常支付，只试了红包，其他情况未尝试

**Comment by Mirr0ch1** [comment]
其他比如 location report enabler、clipboard whitelist 等 riru 模块工作正常。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

**Comment by eritpchy** [comment]
安装这个测试版, 重启后进入微信然后上传/sdcard/riru.log日志文件
[magisk-riru-module-xfingerprint-pay-wechat-v3.9.10-test.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4602875/magisk-riru-module-xfingerprint-pay-wechat-v3.9.10-test.zip)

**Comment by matosman** [comment]
> 安装这个测试版, 重启后进入微信然后上传/sdcard/riru.log日志文件
> [magisk-riru-module-xfingerprint-pay-wechat-v3.9.10-test.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4602875/magisk-riru-module-xfingerprint-pay-wechat-v3.9.10-test.zip)

安装重启后使用微信和支付都没发现sdcard有log生成，v21.2

**Comment by eritpchy** [comment]
再试试这个, 需要配合Riru-core 21.2, 安装后截图上传安装界面, 重启后进入微信然后上传/data/data/com.tencent.mm/files/riru.log日志文件
[magisk-riru-v21.2.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4604994/magisk-riru-v21.2.zip)
[[test]magisk-riru-module-xfingerprint-pay-wechat-v3.9.10.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4604995/test.magisk-riru-module-xfingerprint-pay-wechat-v3.9.10.zip)

**Comment by matosman** [comment]
这次有了riru.log
Line: 240
Line: 240

**Comment by eritpchy** [comment]
就2行?

**Comment by matosman** [comment]
> 就2行?

行数有增加，但是都是同样的内容Line：240

**Comment by eritpchy** [comment]
上传来看看

**Comment by matosman** [comment]
[riru.log](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4605031/riru.log)

**Comment by eritpchy** [comment]
试试这个有没有出现设置界面, 日志文件:/data/data/com.tencent.mm/files/riru1.log
[[test1]magisk-riru-module-xfingerprint-pay-wechat-v3.9.10.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4605034/test1.magisk-riru-module-xfingerprint-pay-wechat-v3.9.10.zip)

**Comment by matosman** [comment]
出来了，也可以支付
![Screenshot_20200510-102933](https://user-images.githubusercontent.com/64797119/81489552-3c7a5580-92a9-11ea-808a-0b3d84f25a92.jpg)

**Comment by eritpchy** [comment]
这是最终版 去掉了日志文件, 看看有没问题
[magisk-riru-module-xfingerprint-pay-wechat-v3.9.11.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4605062/magisk-riru-module-xfingerprint-pay-wechat-v3.9.11.zip)

**Comment by ihkc** [comment]
> 这是最终版 去掉了日志文件, 看看有没问题
> [magisk-riru-module-xfingerprint-pay-wechat-v3.9.11.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4605062/magisk-riru-module-xfingerprint-pay-wechat-v3.9.11.zip)

沒問題了，可以正常使用

**Comment by matosman** [comment]
> 这是最终版 去掉了日志文件, 看看有没问题
> [magisk-riru-module-xfingerprint-pay-wechat-v3.9.11.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/4605062/magisk-riru-module-xfingerprint-pay-wechat-v3.9.11.zip)

除了版本号还是3.9.10其它都正常

**Comment by eritpchy** [comment]
ok

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/commit/df0ae04cbe8a74a84e88256b9ed977b07b90da49
