### ISSUE TITLE
请求适配 Riru V22.0

### ISSUE THREAD

**Issue by WewillChen** [eritpchy/Fingerprint-pay-magisk-wechat#27]
https://github.com/RikkaApps/Riru-ModuleTemplate/blob/master/README.md#api-changes

**Comment by CloudFlash-US** [comment]
两人血书，请求适配 Riru V22.0

**Comment by zetamk4** [comment]
请求+1

**Comment by notorangee** [comment]
四人血书

**Comment by eritpchy** [comment]
忙

**Comment by kn007** [comment]
同求，谢谢

**Comment by ilazycat** [comment]
同求适配

**Comment by y6yuan** [comment]
+1

**Comment by MonwF** [comment]
[riru-module-xfingerprint-pay-wechat-v3.9.20.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/5581947/riru-module-xfingerprint-pay-wechat-v3.9.20.zip)

照着新模板修改了下，目前没发现什么问题 (~~有问题也不懂修改~~)

**Comment by kn007** [comment]
建议PR，谢谢 @MonwF

**Comment by notorangee** [comment]
> [riru模块xfingerprint支付微信v3.9.20.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/5581947/riru-module-xfingerprint-pay-wechat-v3.9.20.zip)
> 
> 照着新模板修改了下，目前没发现什么问题（~有问题也不懂修改~）

谢谢，可用

**Comment by mapleshadow** [comment]
8人血书，哈哈，作者收个费算了，我第一个支持

**Comment by eritpchy** [comment]
=_=#

**Comment by Charles-Kai** [comment]
> > [riru模块xfingerprint支付微信v3.9.20.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/5581947/riru-module-xfingerprint-pay-wechat-v3.9.20.zip)
> > 照着新模板修改了下，目前没发现什么问题（~有问题也不懂修改~）
> 
> 谢谢，可用

你提个pr合并请求算啦，我一用这个软件就赞助了

**Comment by AdoShan** [comment]
> [riru-module-xfingerprint-pay-wechat-v3.9.20.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/5581947/riru-module-xfingerprint-pay-wechat-v3.9.20.zip)
> 
> 照着新模板修改了下，目前没发现什么问题 (~有问题也不懂修改~)

v23可以用吗

**Comment by MonwF** [comment]
> > [riru-module-xfingerprint-pay-wechat-v3.9.20.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/5581947/riru-module-xfingerprint-pay-wechat-v3.9.20.zip)
> > 照着新模板修改了下，目前没发现什么问题 (~有问题也不懂修改~)
> 
> v23可以用吗

刚升级v23后，没什么问题

**Comment by Charles-Kai** [comment]
> > [riru-module-xfingerprint-pay-wechat-v3.9.20.zip](https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/files/5581947/riru-module-xfingerprint-pay-wechat-v3.9.20.zip)
> > 照着新模板修改了下，目前没发现什么问题 (~有问题也不懂修改~)
> 
> v23可以用吗

没试哈，因为指纹开关已经关掉了
