### ISSUE TITLE
微信Play 7.0.3启用模块后导致微信无法启动-模块版本：V3.9.3

### ISSUE THREAD

**Issue by x6326630** [eritpchy/Fingerprint-pay-magisk-wechat#3]
刷入V3.9.3还是不行，微信无法启动。
系统：Pixel 2 XL（Android 9）
Magisk版本：V19.0 
Riru Core版本：V18 
微信版本：谷歌Play 7.0.3 
微信支付 - 微信版本：v3.9.3

**Comment by eritpchy** [comment]
连上电脑
抓取 adb logcat 文件发给我
记得打开一次微信

**Comment by eritpchy** [comment]
测试的时候 Xposed 要关闭

**Comment by cherinyy** [comment]
感觉大概是没问题了？
或许可以把issue关了
