### ISSUE TITLE
【插件安全漏洞】优先加载 /data/local/tmp 下的dex是否欠妥？

### ISSUE THREAD

**Issue by wuyr** [eritpchy/Fingerprint-pay-magisk-wechat#30]
main.cpp：

![image](https://user-images.githubusercontent.com/9758478/101604555-0d44e600-3a3c-11eb-9d92-2525e61ff8d9.png)

这里会优先加载 `/data/local/tmp` 目录下的dex，而这个目录的访问权限是771，也就是无须ROOT也能随便替换dex。

如果我写一个同级包名的类：

![image](https://user-images.githubusercontent.com/9758478/101605256-ecc95b80-3a3c-11eb-9d24-14e0e3103e0f.png)

打包成dex，改名并push到上述目录下：

![image](https://user-images.githubusercontent.com/9758478/101606449-5f870680-3a3e-11eb-9c0e-009f60e26f85.png)

重启微信：

![image](https://user-images.githubusercontent.com/9758478/101605569-4a5da800-3a3d-11eb-8478-a033b7f76110.png)

可以轻易被利用来做坏事

**Comment by eritpchy** [comment]
是的，这个是用来调试的， 介于这个插件比较小众，没有做太多处理， 而且这个目录只有shell用户才能读写，所以相对来说是安全的。

**Comment by eritpchy** [comment]
目前没有时间和精力去做这方面的改动，如果你有条件可以提pr, 但请务必基于gradle开发。

**Comment by wuyr** [comment]
了解。
如果要兼顾免重启更新，我认为可以在打包时，根据variant name来打2个包，一个release一个debug。
具体做法：在preBuild阶段对main.h的一个标记做修改。在main.cpp中获取dex路径前，先检查标记是release or debug，release不加载tmp下的dex。
这样只需要安装一次debug版本，就能一直快速替换dex而不影响release版

**Comment by eritpchy** [comment]
不推荐改h头文件，建议用宏， 而且这个项目我基本也不用debug模式哈哈哈哈哈哈...

**Comment by wuyr** [comment]
Hi！借鉴你的思路，用预编译宏的方式，加了个debug模式： <https://github.com/wuyr/HookwormForAndroid> ，在开启debug模式后，可以免重启安装，不影响release版本。

**Comment by eritpchy** [comment]
👍

**Comment by eritpchy** [comment]
closed
