### ISSUE TITLE
指纹图标问题

### ISSUE THREAD

**Issue by Mark4551124015** [eritpchy/Fingerprint-pay-magisk-wechat#31]
请问大佬可否在下个版本中更新一下指纹图标 使他符合md2设计 这个图标有点突兀 感谢🙏

**Comment by eritpchy** [comment]
所以能发套合适的图标过来吗？

**Comment by Mark4551124015** [comment]
> 所以能发套合适的图标过来吗？
抱歉不了解什么尺寸和格式，这个链接中搜索fingerprint可以下载svg或者png
https://material.io/resources/icons/?icon=fingerprint&style=sharp

**Comment by eritpchy** [comment]
svg可

**Comment by Mark4551124015** [comment]
[](url)

> svg可
这是蓝奏云链接
https://wwa.lanzous.com/iTM6gjsavud
更新了一下 这里面有24 36 48dp三个大小的图标

**Comment by eritpchy** [comment]
fixed,  https://github.com/eritpchy/FingerprintPay/releases/tag/4.0.0
