### ISSUE TITLE
微信 8.0.0 下封禁账号

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [eritpchy/Fingerprint-pay-magisk-wechat#34]
![20210201_192831](https://user-images.githubusercontent.com/63704404/106453052-af74cd80-64c3-11eb-8230-efd6a64b7303.png)

本人并不能确定账号封禁 100% 与贵插件有关，但此账号自注册以来（2020 年 12 月），从未在任何模拟器上登录过。登录客户端均为 Google Play 下载的微信。鄙人亦未曾使用过其他微信插件。

**Comment by 54271** [comment]
play更新微信8.0了吗？我加入beta现在还在7.0.21

**Comment by eritpchy** [comment]
少用Xposed

**Comment by eritpchy** [comment]
无解

**Comment by frnksmdlkedjnfr** [comment]
> play更新微信8.0了吗？我加入beta现在还在7.0.21

我是 play 7.0 被静默更新成 8.0 的

**Comment by SecretRC** [comment]
> > play更新微信8.0了吗？我加入beta现在还在7.0.21
> 
> 我是 play 7.0 被静默更新成 8.0 的

play版的都不能应用内更新你怎么静默更新的8.0，手机自带商场更新的吧
