### ISSUE TITLE
大佬是否有打算出一个脸部识别的模块？

### ISSUE THREAD

**Issue by KGB333** [eritpchy/Fingerprint-pay-magisk-wechat#38]
虽然感觉可能性不大不过也想提一下😂起初用这插件就是因为用pixel，是真的神器，如今换了pixel 4只有脸部识别，没有指纹仪😂尝试过安装模块然后利用fingerface来尝试套娃使用但不成功，就也只是提一下吧，如果不会支持但也非常感谢，毕竟真的神器，只是我机器特殊而已

**Comment by KGB333** [comment]
感觉安全性方面，p4的人脸识别是用了立体点阵技术，安全性跟iPhone一样，应该问题不大？

**Comment by eritpchy** [comment]
没有，相关问题已经回复过了， 需要给我一台pixel4。

**Comment by KGB333** [comment]
> 没有，相关问题已经回复过了， 需要给我一台pixel4。

能理解，非常感谢一直以来的付出

**Comment by eritpchy** [comment]
🤝
