### ISSUE TITLE
请求适配Riru V26.0

### ISSUE THREAD

**Issue by protonmailv5** [eritpchy/Fingerprint-pay-magisk-wechat#40]
如题所示

**Comment by KGB333** [comment]
确实用不了了，辛苦大佬更新支持，十分感谢

**Comment by q736178471** [comment]
同求，大佬适配 新版riru用不了了

**Comment by CrazyNutLz** [comment]
求更新

**Comment by StrideLeo** [comment]
一人血书求更新

**Comment by U11Leung** [comment]
同求更新。。

**Comment by kn007** [comment]
目前最新为Riru 26.1.1，请求适配

**Comment by osinx** [comment]
各位，好消息。尝试修改了下脚本，Riru v26下已经可以使用指纹。项目接受PR不?  @eritpchy https://github.com/osinx/Fingerprint-pay-magisk-wechat/releases

**Comment by KGB333** [comment]
> 各位，好消息。尝试修改了下脚本，Riru v26下已经可以使用指纹。项目接受PR不?  @eritpchy https://github.com/osinx/Fingerprint-pay-magisk-wechat/releases

朋友你好，想了解下这个修改版有在安卓12下测试过吗，我想试但怕翻车

**Comment by eritpchy** [comment]
> 各位，好消息。尝试修改了下脚本，Riru v26下已经可以使用指纹。项目接受PR不? @eritpchy https://github.com/osinx/Fingerprint-pay-magisk-wechat/releases

@osinx  项目即将合并, 请勿PR

**Comment by kn007** [comment]
> > 各位，好消息。尝试修改了下脚本，Riru v26下已经可以使用指纹。项目接受PR不? @eritpchy https://github.com/osinx/Fingerprint-pay-magisk-wechat/releases
> 
> @osinx 项目即将合并, 请勿PR

看起来是好消息？大概什么时候呢？

**Comment by WewillChen** [comment]
> 各位，好消息。尝试修改了下脚本，Riru v26下已经可以使用指纹。项目接受PR不? @eritpchy https://github.com/osinx/Fingerprint-pay-magisk-wechat/releases

riru core v26.1.1 出了点小问题，提示 
unzip: can't change directory to '/data/adb/riru/modules/module_xfingerprint_pay_wechat': No such file or directory
*********************************************************
! riru/module.prop.new not exists
! This zip may be corrupted, please try downloading again
*********************************************************
! Installation failed

**Comment by kn007** [comment]
所以本周会更新吗？

**Comment by KGB333** [comment]
https://topjohnwu.medium.com/state-of-magisk-2021-fe29fdaee458
面具要改版了，估计模块要重新适配了

**Comment by eritpchy** [comment]
> 所以本周会更新吗？

预计本周末前会发布更新

**Comment by eritpchy** [comment]
fixed,  https://github.com/eritpchy/FingerprintPay/releases/tag/4.0.0
