### ISSUE TITLE
微信Play 7.0.3版，模块正常启用，但无法开启指纹支付。

### ISSUE THREAD

**Issue by wangboyu1994** [eritpchy/Fingerprint-pay-magisk-wechat#5]
指纹支付版本：Magisk V3.9.3
手机：OnePlus 7 Pro
系统：Android Pie
Magisk版本：V19.3 (19300)
Riru Core版本：V19.1
微信版本：Google Play 7.0.3
安装情况如下图1，前面步骤一切正常，直到最后一步开启指纹支付时，有下图2提示，曾重新录入过一次全部指纹，但未果，故反馈一下情况。另外我也试过Xposed V3.9.2版本（9.0使用的EdXposed），仍是同样的结果。
![微信图片_20190622224136](https://user-images.githubusercontent.com/28779117/59965329-f3110280-953e-11e9-9ad9-e5183aa32fae.jpg)
![微信图片_20190622224129](https://user-images.githubusercontent.com/28779117/59965334-fc01d400-953e-11e9-8570-484ae5aaa430.jpg)

**Comment by eritpchy** [comment]
你不懂用

**Comment by JohnCanny52** [comment]
此模块不能让你已解锁的设备恢复系统指纹解锁，是验证系统指纹然后帮你输入密码，用之前要先搞清楚实现原理
