### ISSUE TITLE
Missing source code to fingerprint-pay-wechat-magisk.apk

### ISSUE THREAD

**Issue by Mygod** [eritpchy/Fingerprint-pay-magisk-wechat#7]
https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/commits/master/riru-module-xfingerprint-pay-wechat/libs/fingerprint-pay-wechat-magisk.apk

**Comment by eritpchy** [comment]
This is intentionally ,you can find similar code in https://github.com/eritpchy/Xposed-Fingerprint-pay

**Comment by Mygod** [comment]
Being similar still does not justify not including the source code (maybe add a disclaimer that this module is not fully open source).

The more preferrable way would be use a [git submodule](https://github.blog/2016-02-01-working-with-submodules/) (or something similar) and include the build instruction.

**Comment by eritpchy** [comment]
YES NOT OPEN SOURCE！
