### ISSUE TITLE
2019.10.10微信指纹支付失效

### ISSUE THREAD

**Issue by ReddotCleaner** [eritpchy/Fingerprint-pay-magisk-wechat#9]
并非单独事件，在酷安上有多人反映指纹支付失效。如果需要提供任何日志或者帮助排除，我可以帮忙。

**Comment by zscsmasha** [comment]
还以为就我一个人失效了呢。

**Comment by ReddotCleaner** [comment]
> 还以为就我一个人失效了呢。

不，应该算是范围失效了，目前还不知道为什么

**Comment by zscsmasha** [comment]
> > 还以为就我一个人无效了呢。
> 
> 不，应该算是范围无效了，目前还不知道为什么为什么

太极的微信支付能用么？

**Comment by ReddotCleaner** [comment]
> > > 还以为就我一个人无效了呢。
> > 
> > 
> > 不，应该算是范围无效了，目前还不知道为什么为什么
> 
> 太极的微信支付能用么？

![GQS%CP96_UJ)7}LTC5FH{AC](https://user-images.githubusercontent.com/34325738/66549536-0f7c8d80-eb76-11e9-9029-201b38b5f4ff.jpg)
应该是不行

**Comment by zscsmasha** [comment]
> > > > 还以为就我一个人无效了呢。
> > > 
> > > 
> > > 不，应该算是范围无效了，目前还不知道为什么为什么
> > 
> > 
> > 太极的微信支付能用么？
> 
> ![GQS％CP96_UJ）7} LTC5FH {AC](https://user-images.githubusercontent.com/34325738/66549536-0f7c8d80-eb76-11e9-9029-201b38b5f4ff.jpg)
> 应该是不行

我之前倒是用过覆盖安装包试过并成功使用，但是那是7.0.6的事了，7.0.7就不行了，也不知道是不是作者的模块的事，所以就来看看的，没想到还是有人跟我一样失效。

**Comment by like1020** [comment]
失效+1

**Comment by LeehsinZhang** [comment]
play版本还是7.05

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-wechat/releases/tag/3.9.4
